### ISSUE TITLE
Disallow dragging and dropping vice versa

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [carlosjorger/vue-fluid-dnd#19]
Hello @carlosjorger , I would like to let you know that after using many libraries I found that this one is the best. thank u

but I think there is something missing, I want to let the user be able to move cards from list1 to list2 but not from list2 to list1 while keeping the sorting option available for both, is this applicable?

**Comment by carlosjorger** [comment]
Not for the moment, thanks for the feedback

**Comment by carlosjorger** [comment]
Hello @AmmarMohamadIsmaeel , now using the version 0.8.0 adding more than one group you can solve the problem. Check the doc https://vue-fluid-dnd.netlify.app/guides/listgroup/
