### ISSUE TITLE
Got an usability error on Firefox - Touch Events

### ISSUE THREAD

**Issue by armando-herastang** [carlosjorger/vue-fluid-dnd#3]
I was trying the [examples](https://vue-fluid-dnd.netlify.app/example/vertical-list/single-vertical-list/). But I couldn't drag and drop. I am using Firefox (v.124.0.1). I checked the console and I got this:

```
Uncaught ReferenceError: TouchEvent is not defined
    Be https://vue-fluid-dnd.netlify.app/_astro/_plugin-vue_export-helper.BrKkVjjl.js:1
    K https://vue-fluid-dnd.netlify.app/_astro/_plugin-vue_export-helper.BrKkVjjl.js:1
    N https://vue-fluid-dnd.netlify.app/_astro/_plugin-vue_export-helper.BrKkVjjl.js:1
```

I searched a little and apparently I needed to enabled touch events for Firefox. Mainly, this setting

```dom.w3c_touch_events.enabled``` 

on the `about:config` page.

It has 3 states:

> 0 - disable
> 1 - enable
> 2 - auto-detect

In my case, it was in `auto-detect` but didn't work the TouchEvents, So I changed it to `1` (enable) and it works perfectly.

Perhaps you should include this somewhere in the docs for Firefox users. (also check Safari)

Bests, 
Keep up the good work

**Comment by carlosjorger** [comment]
Interesting, I'm going to reproduce that case in playwright and look for a solution. Thank you very much for the feedback. Safari is a box of surprises 😅 I know.
