### ISSUE TITLE
mouse not in the drag element, the arrow go away from the square.

### ISSUE THREAD

**Issue by ijry** [carlosjorger/vue-fluid-dnd#6]
https://github.com/carlosjorger/vue-fluid-dnd/assets/3102798/ba988904-b128-4aa5-aeb5-b69c41027dc4

**Comment by carlosjorger** [comment]
Can you send me the code you used to identify the problem so I can replicate it? It could be that some default style is displacing the elements, or it could be some scroll displacement that is not being taken into account(the library I mean).

**Comment by ijry** [comment]
the core code like this

`
          <div v-show="!state.toolsBarShow"
            class="poster-pages p-3 pt-0 bg-gray-50 overflow-y-auto" style="width: 180px;">
            <el-divider direction="horizontal" content-position="left">页面</el-divider>
            <ul class="page-warp blobk" ref="parent">
              <li class="page-item cursor-pointer hover:shadow hover:border-sky-300 bg-white mb-2 relative border-solid border-1"
                :class="{'border-sky-400': index == pageIndex}"
                v-for="(item,index) in pageData" :index="index" :key="index" @click="togglePage(index)">
                <Thumbnail :template="item.data" :size="152"></Thumbnail>
                <h3 class="absolute bottom-0 right-0 text-xs text-center py-1 text-white w-full"
                  @click="openNameEdit(index)">
                  {{item.name}}
                </h3>
                <div class="actions hidden absolute top-0 right-0 bg-black/50 rounded p-1 flex justify-center items-center">
                  <el-icon class="mx-1" @click="copyPage(index)"><ElIconCopyDocument class="text-white hover:gray-100" /></el-icon>
                  <el-icon class="mx-1" @click="delPage(index)"><ElIconDelete class="text-white hover:gray-100" /></el-icon>
                </div>
              </li>
            </ul>
          </div>`

**Comment by ijry** [comment]
hi , will this code any help?

**Comment by carlosjorger** [comment]
I have an idea of what the problem is, but I haven't started working on it yet I have been working on a new feature these days. I will prioritize this error later👍

**Comment by ijry** [comment]
thks👍

**Comment by carlosjorger** [comment]
update to latest version and try again
